import type { SkillCategory } from "@/types";

export const skillCategories: SkillCategory[] = [
  {
    title: "Core Languages",
    icon: "fas fa-code",
    skills: [
      {
        name: "JavaScript",
        subtitle: "ES6+ & Async",
        icon: "fa-brands fa-js",
        color: "text-yellow-400",
        borderHover: "hover:border-yellow-400/50",
      },
      {
        name: "TypeScript",
        subtitle: "Type Safety",
        icon: "fas fa-file-code",
        color: "text-blue-400",
        borderHover: "hover:border-blue-400/50",
      },
      {
        name: "HTML5 & CSS3",
        subtitle: "UI Fundamentals",
        icon: "fa-brands fa-html5",
        color: "text-orange-500",
        borderHover: "hover:border-orange-500/50",
      },
      {
        name: "Python",
        subtitle: "Scripting",
        icon: "fa-brands fa-python",
        color: "text-yellow-300",
        borderHover: "hover:border-yellow-300/50",
      },
      {
        name: "SQL",
        subtitle: "PostgreSQL / MySQL",
        icon: "fas fa-database",
        color: "text-blue-300",
        borderHover: "hover:border-blue-300/50",
      },
    ],
  },
  {
    title: "Frontend Architecture",
    icon: "fas fa-layer-group",
    skills: [
      {
        name: "React.js",
        subtitle: "Component UI",
        icon: "fa-brands fa-react",
        color: "text-cyan-400",
        borderHover: "hover:border-cyan-400/50",
      },
      {
        name: "Next.js",
        subtitle: "App Router & SSR",
        icon: "fas fa-n",
        color: "text-white",
        borderHover: "hover:border-white/50",
      },
      {
        name: "Redux / Zustand",
        subtitle: "State Management",
        icon: "fas fa-cubes",
        color: "text-purple-400",
        borderHover: "hover:border-purple-400/50",
      },
      {
        name: "Tailwind CSS",
        subtitle: "Utility-First Styling",
        icon: "fas fa-wind",
        color: "text-teal-400",
        borderHover: "hover:border-teal-400/50",
      },
      {
        name: "React Query",
        subtitle: "Data Fetching",
        icon: "fas fa-bolt",
        color: "text-red-400",
        borderHover: "hover:border-red-400/50",
      },
    ],
  },
  {
    title: "Backend Architecture",
    icon: "fas fa-server",
    skills: [
      {
        name: "Node.js",
        subtitle: "JavaScript Runtime",
        icon: "fa-brands fa-node-js",
        color: "text-green-500",
        borderHover: "hover:border-green-500/50",
      },
      {
        name: "Express.js",
        subtitle: "RESTful APIs",
        icon: "fas fa-server",
        color: "text-gray-400",
        borderHover: "hover:border-gray-400/50",
      },
      {
        name: "MongoDB",
        subtitle: "NoSQL Database",
        icon: "fas fa-leaf",
        color: "text-green-600",
        borderHover: "hover:border-green-600/50",
      },
      {
        name: "Mongoose",
        subtitle: "Data Modeling",
        icon: "fas fa-project-diagram",
        color: "text-red-500",
        borderHover: "hover:border-red-500/50",
      },
      {
        name: "JWT & OAuth",
        subtitle: "Auth & Security",
        icon: "fas fa-shield-alt",
        color: "text-indigo-400",
        borderHover: "hover:border-indigo-400/50",
      },
    ],
  },
  {
    title: "Cloud & DevOps",
    icon: "fas fa-cloud",
    skills: [
      {
        name: "Git & GitHub",
        subtitle: "Version Control",
        icon: "fa-brands fa-github",
        color: "text-white",
        borderHover: "hover:border-white/50",
      },
      {
        name: "Supabase / Firebase",
        subtitle: "Backend-as-a-Service",
        icon: "fas fa-bolt",
        color: "text-amber-500",
        borderHover: "hover:border-amber-500/50",
      },
      {
        name: "Postman",
        subtitle: "API Testing",
        icon: "fas fa-rocket",
        color: "text-orange-500",
        borderHover: "hover:border-orange-500/50",
      },
      {
        name: "Vite / Webpack",
        subtitle: "Build Tooling",
        icon: "fas fa-box-open",
        color: "text-yellow-400",
        borderHover: "hover:border-yellow-400/50",
      },
      {
        name: "AWS / Vercel",
        subtitle: "Hosting & CI/CD",
        icon: "fa-brands fa-aws",
        color: "text-orange-400",
        borderHover: "hover:border-orange-400/50",
      },
    ],
  },
  {
    title: "AI / GenAI",
    icon: "fas fa-brain",
    skills: [
      {
        name: "OpenAI API",
        subtitle: "LLM Integration",
        icon: "fas fa-robot",
        color: "text-emerald-400",
        borderHover: "hover:border-emerald-400/50",
      },
      {
        name: "Claude API (Anthropic)",
        subtitle: "Cognitive Tasks",
        icon: "fas fa-brain",
        color: "text-amber-500",
        borderHover: "hover:border-amber-500/50",
      },
      {
        name: "Google Gemini 1.5",
        subtitle: "Multimodal AI",
        icon: "fas fa-magic",
        color: "text-blue-400",
        borderHover: "hover:border-blue-400/50",
      },
      {
        name: "LangChain",
        subtitle: "LLM Orchestration",
        icon: "fas fa-link",
        color: "text-green-400",
        borderHover: "hover:border-green-400/50",
      },
      {
        name: "Prompt Engineering",
        subtitle: "Context Design",
        icon: "fas fa-terminal",
        color: "text-cyan-400",
        borderHover: "hover:border-cyan-400/50",
      },
      {
        name: "Agentic Workflows",
        subtitle: "Autonomous Agents",
        icon: "fas fa-network-wired",
        color: "text-purple-400",
        borderHover: "hover:border-purple-400/50",
      },
    ],
  },
  {
    title: "Payments & Auth",
    icon: "fas fa-shield-alt",
    skills: [
      {
        name: "Razorpay",
        subtitle: "Payment Gateway",
        icon: "fas fa-credit-card",
        color: "text-blue-500",
        borderHover: "hover:border-blue-500/50",
      },
      {
        name: "Stripe",
        subtitle: "Global Payments",
        icon: "fa-brands fa-stripe",
        color: "text-indigo-500",
        borderHover: "hover:border-indigo-500/50",
      },
      {
        name: "Clerk",
        subtitle: "User Management",
        icon: "fas fa-user-shield",
        color: "text-blue-400",
        borderHover: "hover:border-blue-400/50",
      },
      {
        name: "JWT",
        subtitle: "Token-Based Auth",
        icon: "fas fa-key",
        color: "text-pink-500",
        borderHover: "hover:border-pink-500/50",
      },
    ],
  },
];